### ISSUE TITLE
Learn how to use Play Framework

### ISSUE THREAD

**Issue by vincentvictor** [SSD2015/TeamFatCat#10]
Everybody learns how to use Play Framework

**Comment by dtinth** [comment]
On GitHub, you can only assign one person to issue. One way to work around this is to use [GitHub's Task List](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments) feature — by creating one task per person.

**Comment by dtinth** [comment]
By the way, how much will you learn the Play framework before considering this task "done?"

Of course, you don't have to learn the **whole** framework to be able to start working on the webapp, and learning is a continuous, lifelong process.

So for this task you have to set a goal of "how much to learn."
